// Code generated by cmd/reset. DO NOT EDIT.

package models

func (receiver *TestResetStruct) Reset() {
	if receiver == nil {
		return
	}

	receiver.Counter = 0
	receiver.Name = ""
	receiver.Active = false
	receiver.Tags = receiver.Tags[:0]
	clear(receiver.Data)
	if receiver.Value != nil {
		if resetter, ok := interface{}(receiver.Value).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Value = 0
		}
	}
}

func (receiver *ComplexResetStruct) Reset() {
	if receiver == nil {
		return
	}

	receiver.ID = 0
	receiver.Label = ""
	receiver.Items = receiver.Items[:0]
	clear(receiver.Config)
	if receiver.Child != nil {
		if resetter, ok := interface{}(receiver.Child).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Child = TestResetStruct{}
		}
	}
	if receiver.ChildPtr != nil {
		if resetter, ok := interface{}(receiver.ChildPtr).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.ChildPtr = ComplexResetStruct{}
		}
	}
}
