// Code generated by cmd/reset. DO NOT EDIT.

package main

func (receiver *ExampleStruct) Reset() {
	if receiver == nil {
		return
	}

	receiver.ID = 0
	receiver.Name = ""
	receiver.Active = false
	receiver.Tags = receiver.Tags[:0]
	clear(receiver.Metadata)
}

func (receiver *PointerStruct) Reset() {
	if receiver == nil {
		return
	}

	if receiver.Value != nil {
		if resetter, ok := interface{}(receiver.Value).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Value = 0
		}
	}
	if receiver.Text != nil {
		if resetter, ok := interface{}(receiver.Text).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Text = ""
		}
	}
	if receiver.Config != nil {
		if resetter, ok := interface{}(receiver.Config).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Config = ExampleStruct{}
		}
	}
}

func (receiver *NestedStruct) Reset() {
	if receiver == nil {
		return
	}

	receiver.Parent = ""
	receiver.Children = receiver.Children[:0]
	if receiver.Primary != nil {
		if resetter, ok := interface{}(receiver.Primary).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*receiver.Primary = PointerStruct{}
		}
	}
}
